mode: auto

branchName: 'i${issue.number}-${issue.title[0,64],}'

gitSafeReplacementChar: '-'

defaultBranch: 'develop'

silent: true
autoCloseIssue: true

branches:
  - label:
      - bug
      - production
    prefix: hotfix/
    name: main
    prTarget:
      - main
      - develop
  - label:
      - bug
      - development
    prefix: bugfix/
    name: develop
    prTarget: develop
  - label:
      - enhancement
    prefix: feature/
    name: develop
    prTarget: develop
  - label: '*'
    skip: true
