mode: auto

branchName: '${issue.number}-${issue.title[0,64],}'

gitSafeReplacementChar: '-'

# silent: true # Remove comments by the app
autoLinkIssue: true
autoCloseIssue: true

defaultBranch: 'develop'

conventionalPrTitles: true

copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true

branches:
  - label:
      - Epic
    skip: true
  - label:
      - bug
    name: develop
    prefix: bugfix/
    prTarget: develop
  - label:
      - enhancement
    name: develop
    prefix: feature/
    prTarget: develop
  - label: '*'
    skip: true
